[tool.black]
line-length = 119
extend-exclude = "(migrations|manage.py|asgi.py|wsgi.py)"

[tool.isort]
line_length = 119
profile = "black"
skip_gitignore = true
extend_skip_glob = ["**/migrations/*","manage.py","asgi.py","wsgi.py"]

[tool.ruff]
extend-exclude = ["**/migrations/*", "manage.py", "asgi.py", "wsgi.py"]
line-length = 119

[tool.ruff.lint]
select = ["E", "W", "F", "I", "DJ", "C901"]
ignore = ["E203"]

[tool.pyright]
# ignore = ["**"]
