# Generated by Django 4.2.16 on 2024-11-10 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="like_users",
            field=models.ManyToManyField(related_name="like_tweets", to=settings.AUTH_USER_MODEL),
        ),
    ]
